version: '3'

services:
  node-app:
    build: .
    restart: unless-stopped
    ports:
      - "3014:3014"
    depends_on:
      - mysql-db
    env_file:
      - .env
    environment:
      - PLACEHOLDER=YES
    image: "nheek/lookatme:latest" 

  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "4014:3306"
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - .sql_data:/docker-entrypoint-initdb.d/