version: '3'

services:
  node-app:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - mysql-db
    env_file:
      - .env
    environment:
      - PLACEHOLDER=YES

  mysql-db:
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql