version: "3"

services:
  node-app:
    build: .
    restart: unless-stopped
    ports:
      - "3002:3001"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PLACEHOLDER=YES
    image: "reg.nheek.com/nheek/lookatme:latest"

  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PLACEHOLDER: "YES"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - .sql_data:/docker-entrypoint-initdb.d/

volumes:
  postgres_db_data:
