name: Build, Push, and Deploy Docker Compose

on:
  push:
    branches:
      - actions-test

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate .env file
        run: |
          # Create a .env file with sensitive information
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env

      - name: Create Docker Compose file
        run: |
          # Create a basic docker-compose.yml file
          echo "version: '3'" >> docker-compose.yml
          echo "services:" >> docker-compose.yml
          echo "  your-service:" >> docker-compose.yml
          echo "    image: ${{ secrets.DOCKERHUB_USERNAME }}/lookatme:latest" >> docker-compose.yml
          # Add other necessary configurations

      - name: Build and Push Docker Images
        run: |
          # Log in to Docker Hub and push the images
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Deploy the Docker Compose project on the remote server
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d
