name: Build, Push, and Deploy Docker Compose

on:
  push:
    branches:
      - actions-test

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Change to the appropriate directory
            cd apps/lookatme/

            # Pull the Docker Compose project on the remote server
            docker-compose pull ${{ secrets.DOCKERHUB_USERNAME }}/lookatme:latest
            docker-compose pull mysql
            git pull origin main
            docker-compose down
            docker-compose build
            docker-compose up -d
  